const legends=[['001','食','黒潮町','潮風が育てる、幻の黒糖。','火入れは一年に、ほんの数日。','sun','◒'],['012','祭り','香南市','夜空を焦がす、絵金の町。','闇の中でだけ、屏風絵が目を覚ます。','night','火'],['027','職人','土佐市','海を渡った、和紙の手ざわり。','千年の流れを、指先ですくう人。','paper','紙']];
const cats=[['食','うまいは、物語だ。','箸'],['酒','一献に、土地が宿る。','酉'],['職人','手の中に、時がある。','手'],['祭り','一年に一度、町が燃える。','火'],['絶景','言葉をなくす、場所へ。','山'],['人','会うために、旅をする。','人']];
document.querySelector('#root').innerHTML=`<main>
<nav class="nav"><button class="brand" data-go="top"><span class="brand-mark">伝</span><span>コウチの伝説<small>LEGENDS OF KOCHI</small></span></button><div class="nav-links"><button data-go="today">今日の伝説</button><button data-go="zukan">伝説図鑑</button><button data-go="map">地図から探す</button><button data-go="join">伝説を教える</button></div><button class="menu-btn" aria-label="メニュー">☰</button></nav>
<div class="mobile-menu">${[['today','今日の伝説'],['zukan','伝説図鑑'],['map','地図から探す'],['join','伝説を教える']].map(x=>`<button data-go="${x[0]}">${x[1]}</button>`).join('')}</div>
<header id="top" class="hero"><div class="title-stage"><img src="./kochi-title-screen.png" alt="ファミコンゲーム風に描かれたコウチの伝説のタイトル画面"><div class="hero-shade"></div></div><div class="game-console"><div class="game-hud"><div class="level-box"><small>ADVENTURER LEVEL</small><strong><i>LV.</i>01</strong><span>かけだし冒険者</span></div><div class="status-box"><span><small>発見した伝説</small><b>036</b><i>/ 100</i></span><span><small>エリア</small><b>04</b><i> DISCOVERED</i></span></div><div class="hp-box"><small>HP</small><b>♥ ♥ ♥</b><span>ぜんかい</span></div></div><div class="hero-copy"><p>▶ ぼうけんの準備ができました</p><button class="primary" data-go="today">PRESS START</button><small>🔊 音量をオンにしてタップ</small></div></div></header>
<section id="today" class="today section"><div class="section-kicker"><span>QUEST 01 / きょうの でんせつ</span><i></i></div><div class="today-grid"><div class="today-title"><p>7月28日の発見</p><h2>今日の<br><strong>伝説。</strong></h2><div class="day-stamp"><b>▣</b><span>毎日、ひとつ。<br><b>高知の物語を更新。</b></span></div></div><article class="feature-card"><div class="feature-art"><span>四万十の<br>青のり</span><b>001</b></div><div class="feature-body"><div class="meta"><span>食</span><span>📍 四万十市</span></div><h3>川の香りを、<br>春の食卓へ。</h3><p>一年のうち、いちばん寒い季節。四万十川の河口で、鮮やかな緑がゆらめく。地元の人が待ちわびる、短い旬の物語。</p><button id="read-legend">▶ この伝説を読む</button></div></article></div></section>
<section class="latest section"><div class="heading-row"><div><p class="eyebrow dark">NEW LEGENDS</p><h2>あたらしい伝説</h2></div><button>すべて見る →</button></div><div class="legend-grid">${legends.map(l=>`<article class="legend-card ${l[5]}"><div class="legend-visual"><b>${l[6]}</b><span>LEGEND<br>No.${l[0]}</span></div><div class="legend-content"><div class="meta"><span>${l[1]}</span><span>📍 ${l[2]}</span></div><h3>${l[3]}</h3><p>${l[4]}</p><span class="card-arrow">→</span></div></article>`).join('')}</div></section>
<section class="season"><div class="season-copy"><p class="eyebrow">SEASONAL LEGEND / SUMMER</p><h2>夏は、<br>一瞬で過ぎてゆく。</h2><p>今だけ会える伝説を、見逃さないように。</p><button>夏の伝説を探す →</button></div><div class="fireflies">${'<i></i>'.repeat(8)}</div></section>
<section id="zukan" class="zukan"><div class="section inner"><div class="section-kicker light"><span>THE LEGEND ARCHIVES</span><i></i></div><div class="zukan-head"><div><h2>伝説図鑑</h2><p>気になる入口から、冒険へ。</p></div><span class="number">036<small>DISCOVERED</small></span></div><div class="category-grid">${cats.map(c=>`<button><span class="category-icon">${c[2]}</span><span><b>${c[0]}</b><small>${c[1]}</small></span><span class="cat-arrow">→</span></button>`).join('')}</div></div></section>
<section id="map" class="map-section section"><div class="map-copy"><p class="eyebrow dark">EXPLORE THE MAP</p><h2>地図をひらけば、<br>冒険がはじまる。</h2><p>山を越え、川をくだり、海へ。<br>場所から、まだ知らない物語を探そう。</p><div class="areas">${[['東部',8],['中央部',14],['西部',6],['四万十',8]].map((a,i)=>`<button class="${i===1?'active':''}" data-area="${a[0]}">${a[0]}<small>${a[1]} LEGENDS</small></button>`).join('')}</div></div><div class="map-art"><div class="map-shape">${[['室戸岬','84%','29%','東部'],['高知市','49%','31%','中央部'],['仁淀川','38%','48%','中央部'],['四万十','17%','70%','四万十']].map((p,i)=>`<button data-pin="${p[3]}" class="${i===1||i===2?'hot':''}" style="left:${p[1]};top:${p[2]}"><i></i><span>${p[0]}</span></button>`).join('')}</div><div class="map-legend">⌖ <span>選択中：<b id="area-label">中央部</b></span></div></div></section>
<section id="community" class="community section"><div class="section-kicker"><span>みんなの でんせつ</span><i></i></div><div class="heading-row"><div><p class="eyebrow dark">ADVENTURERS' LOG</p><h2>冒険者の記録</h2></div><span class="post-count" id="post-count">000 POSTS</span></div><div id="community-empty" class="community-empty"><b>▶ まだ投稿はありません</b><p>最初の伝説を、冒険手帳に記録しよう。</p></div><div id="community-grid" class="community-grid"></div></section>
<section id="join" class="join section"><div class="join-mark"><b>✦</b><span>いいもの<br>ファンクラブ</span></div><p class="eyebrow dark">JOIN THE QUEST</p><h2>あなたの「誰かに教えたい」を、<br>次の伝説に。</h2><p>有名じゃなくていい。ランキングも、点数もない。<br>あなたの心に残った高知を、私たちに教えてください。</p><button id="join-btn">▶ 伝説を投稿する</button></section>
<dialog id="post-dialog" class="post-dialog"><form id="post-form"><div class="dialog-head"><div><small>NEW QUEST</small><h2>伝説を記録する</h2></div><button type="button" id="close-dialog" aria-label="閉じる">×</button></div><p class="dialog-note">あなたが誰かに語りたくなる、高知の物語を教えてください。</p><label><span>📍 場所</span><input name="place" required maxlength="40" placeholder="例：四万十市"></label><label><span>📖 伝説</span><input name="legend" required maxlength="60" placeholder="例：川の香りを運ぶ、春の青のり"></label><label><span>✨ なぜ伝説なのか</span><textarea name="why" required maxlength="240" rows="4" placeholder="心に残った理由や物語"></textarea></label><label><span>🎒 どうやって会えるか</span><textarea name="access" required maxlength="180" rows="3" placeholder="時期、行き方、会うためのヒント"></textarea></label><label><span>なまえ（任意）</span><input name="author" maxlength="30" placeholder="名もなき冒険者"></label><div class="form-status" id="form-status" aria-live="polite"></div><button class="submit-post" type="submit">▶ 冒険手帳に記録する</button><small class="save-note">このプロトタイプでは、投稿はこの端末内に保存されます。</small></form></dialog>
<footer><div class="footer-brand"><span class="brand-mark">伝</span><div><b>コウチの伝説</b><small>まだ、誰も知らない高知に出会う。</small></div></div><p>高知で一番ワクワクする冒険メディアを目指して。</p><span>© 2026 LEGENDS OF KOCHI</span></footer></main>`;
const menu=document.querySelector('.mobile-menu'),menuButton=document.querySelector('.menu-btn');
menuButton.onclick=()=>{const open=menu.classList.toggle('open');menuButton.textContent=open?'×':'☰'};
let gameAudioContext;
const getAudioContext=()=>{const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return null;gameAudioContext??=new AudioCtx();return gameAudioContext};
const unlockAudio=async()=>{const ctx=getAudioContext();if(ctx?.state==='suspended')await ctx.resume();return ctx};
const playStartSound=async()=>{
  const ctx=await unlockAudio();if(!ctx)return false;
  const master=ctx.createGain();master.connect(ctx.destination);master.gain.setValueAtTime(.28,ctx.currentTime);master.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.25);
  const notes=[261.63,329.63,392,523.25,659.25,783.99,1046.5];
  notes.forEach((freq,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain(),t=ctx.currentTime+i*.105;osc.type='square';osc.frequency.setValueAtTime(freq,t);gain.gain.setValueAtTime(.001,t);gain.gain.linearRampToValueAtTime(.22,t+.012);gain.gain.setValueAtTime(.22,t+.072);gain.gain.exponentialRampToValueAtTime(.001,t+.102);osc.connect(gain);gain.connect(master);osc.start(t);osc.stop(t+.11)});
  const bass=ctx.createOscillator(),bassGain=ctx.createGain();bass.type='triangle';bass.frequency.setValueAtTime(130.81,ctx.currentTime);bass.frequency.exponentialRampToValueAtTime(261.63,ctx.currentTime+.72);bassGain.gain.setValueAtTime(.12,ctx.currentTime);bassGain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.8);bass.connect(bassGain);bassGain.connect(master);bass.start();bass.stop(ctx.currentTime+.82);
  return true;
};
const startButton=document.querySelector('.primary');
startButton.addEventListener('pointerdown',()=>{unlockAudio()},{passive:true});
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=async()=>{const start=b.classList.contains('primary');if(start){const sounded=await playStartSound();b.textContent=sounded?'♪ GAME START!':'GAME START!';document.body.classList.add('game-starting');setTimeout(()=>{document.body.classList.remove('game-starting');b.textContent='PRESS START'},900)}setTimeout(()=>document.getElementById(b.dataset.go)?.scrollIntoView({behavior:'smooth'}),start?700:0);menu.classList.remove('open');menuButton.textContent='☰'});
document.querySelector('#read-legend').onclick=e=>e.currentTarget.innerHTML='冒険手帳に記録しました ✓';
const dialog=document.querySelector('#post-dialog'),postForm=document.querySelector('#post-form'),communityGrid=document.querySelector('#community-grid'),emptyState=document.querySelector('#community-empty');
const getPosts=()=>{try{return JSON.parse(localStorage.getItem('kochi-legends-posts')||'[]')}catch{return[]}};
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const renderPosts=()=>{const posts=getPosts();document.querySelector('#post-count').textContent=String(posts.length).padStart(3,'0')+' POSTS';emptyState.hidden=posts.length>0;communityGrid.innerHTML=posts.map((p,i)=>`<article class="community-card"><div class="quest-no">QUEST ${String(posts.length-i).padStart(3,'0')}</div><div class="meta"><span>投稿</span><span>📍 ${escapeHtml(p.place)}</span></div><h3>${escapeHtml(p.legend)}</h3><dl><dt>✨ なぜ伝説？</dt><dd>${escapeHtml(p.why)}</dd><dt>🎒 会いかた</dt><dd>${escapeHtml(p.access)}</dd></dl><footer><span>BY ${escapeHtml(p.author||'名もなき冒険者')}</span><time>${escapeHtml(p.date)}</time></footer></article>`).join('')};
document.querySelector('#join-btn').onclick=()=>dialog.showModal();
document.querySelector('#close-dialog').onclick=()=>dialog.close();
dialog.onclick=e=>{if(e.target===dialog)dialog.close()};
postForm.onsubmit=e=>{e.preventDefault();const data=new FormData(postForm),posts=getPosts();posts.unshift({place:data.get('place').trim(),legend:data.get('legend').trim(),why:data.get('why').trim(),access:data.get('access').trim(),author:data.get('author').trim(),date:new Intl.DateTimeFormat('ja-JP').format(new Date())});localStorage.setItem('kochi-legends-posts',JSON.stringify(posts));document.querySelector('#form-status').textContent='✓ 伝説を記録しました！';renderPosts();setTimeout(()=>{dialog.close();postForm.reset();document.querySelector('#form-status').textContent='';document.querySelector('#community').scrollIntoView({behavior:'smooth'})},650)};
renderPosts();
document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-area]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#area-label').textContent=b.dataset.area;document.querySelectorAll('[data-pin]').forEach(p=>p.classList.toggle('hot',p.dataset.pin===b.dataset.area))});
